name: Deploy Statamic SSG to AWS S3 + CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: |
          composer install
          npm install

      - name: Set environment variables
        run: |
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
          echo "APP_URL=https://main.d2fjryx00g2zv.amplifyapp.com" >> .env

      - name: Compile assets
        run: |
          npm run build

      - name: Generate Static Site
        run: php please ssg:generate

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-central-1'
          S3_BUCKET_NAME: 'statamic-ssg'
        run: |
          aws s3 sync ./storage/app/static s3://$S3_BUCKET_NAME --delete --exact-timestamps

      - name: Invalidate CloudFront Cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-central-1'
          CLOUDFRONT_DISTRIBUTION_ID: 'E2R0TXVPBBPM0M'
        run: |
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
